### ISSUE TITLE
Deployer v7.4.0 breaks mittwald_app function

### ISSUE THREAD

**Issue by Starraider** [mittwald/deployer-recipes#127]
I have a multiple environments setup like:
`mittwald_app('xxxmy-app-id-xxxx-xxxxxx', hostname: 'beta')
    ->set('branch', 'develop')
    ->set('mittwald_domains', ['my-domain.de']);`

This works fine with deployer v7.3.3.
After updating deployer to v7.4.0 I get the error message: "hostname 'beta' could not be resolved".
It looks like ssh is trying to directly connect to "beta", instead of using the app-id.
After switching back to deployer v7.3.3, it works again.

Comment: Maybe you should use "host" instead of "hostname" like deployer does, so that it doesn't get confused with deployers "hostname" parameter?

**Comment by martin-helmich** [comment]
Thanks for the report, I'll investigate-- and also see if we can think of a test case to prevent this from happening again. 🤔
