### ISSUE TITLE
Error: could not get app

### ISSUE THREAD

**Issue by Starraider** [mittwald/deployer-recipes#22]
Hi!
I am currently testing your deployer-recipes.
I have installed a PHP app in the p-pey4f8 project and set a MITTWALD_API_TOKEN environment variable locally.

My deploy.php looks like this:

```php
namespace Deployer;

require 'recipe/composer.php';
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/mittwald/deployer-recipes/recipes/deploy.php';

set('repository', 'https://github.com/Starraider/devViteTypo3.git');

mittwald_app('p-pey4f8')
    ->set('public_path', '/public');
```
If I then execute "vendor/bin/dep deploy -vv", I get the error message:
"Exception in AppRecipe.php on line 86: could not get app"

The -vv output looks like this:
```bash
task deploy:info
[mittwald] info deploying HEAD
done on mittwald
done deploy:info 100ms
task mittwald:discover
[mittwald] Exception in AppRecipe.php on line 86:
[mittwald]
[mittwald] could not get app
[mittwald]
done mittwald:discover 714ms
ERROR: Task mittwald:discover failed!
task deploy:failed
done on mittwald
done deploy:failed 135ms
```
Any idea what could be causing this?

**Comment by martin-helmich** [comment]
Hey Sven! The ID provided to the `mittwald_app` function must be the ID of the _app_, not the _project_ (when using the [CLI](https://github.com/mittwald/cli), you can retrieve that ID via the `mw app list` command). Furthermore, the provided ID must be the actual ID (which is a UUIDv4), and not the short ID (which is provided for convenience, and can -- currently! -- not be queried efficiently via the API).

On a side note, I'll also see if we can get the error message to provide a bit more context as to which input values are expected. 😉 

Hope that helps!

**Comment by martin-helmich** [comment]
In #27, we added some basic checks to user inputs and improved the error messages a bit, so this should be a bit clearer in the future.

I'll close this issue for now, but feel free to reopen. 🙂
